# Generated by Django 2.0.4 on 2018-04-25 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(db_index=True, max_length=200, verbose_name='Name')),
                ('category_slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'category',
                'ordering': ('category_name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=200, verbose_name='Name')),
                ('product_slug', models.SlugField(max_length=200, verbose_name='Slug')),
                ('product_image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('product_description', models.TextField(blank=True, verbose_name='Description')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_stock', models.PositiveIntegerField()),
                ('product_available', models.BooleanField(default=True)),
                ('product_created', models.DateTimeField(auto_now_add=True)),
                ('product_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product',
                'ordering': ('product_name',),
            },
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together={('product_slug', 'id')},
        ),
    ]
